spring.application.name=gateway

server.port=8080

app.secret-key=clientb-secret-change-me-in-production

# Auth Service
spring.cloud.gateway.server.webflux.routes[0].id=authentification-service
spring.cloud.gateway.server.webflux.routes[0].uri=http://clientb-auth-service:8080
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/user/**
spring.cloud.gateway.server.webflux.routes[0].filters[0]=StripPrefix=0

# Product Service
spring.cloud.gateway.server.webflux.routes[1].id=product-service
spring.cloud.gateway.server.webflux.routes[1].uri=http://clientb-product-service:8080
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/product/**
spring.cloud.gateway.server.webflux.routes[1].filters[0]=StripPrefix=0