# ================================
# Client A - Variables
# ================================

# Identité client
client_name: "Entreprise A"
client_siege: "Isotry"
client_prefix: "clienta"

# Ports exposés
front_port: "8080"
gateway_port: "8081"
auth_db_port: "5433"
product_port: "5001"
product_db_port: "5434"

# Base de données Auth
auth_db_user: "postgres"
auth_db_password: "clienta_auth_pass"
auth_db_name: "clienta_authentication_db"

# Base de données Product
product_db_user: "postgres"
product_db_password: "clienta_product_pass"
product_db_name: "clienta_product_db"

# JWT
jwt_secret: "clienta-secret-change-me-in-production"
jwt_issuer: "AuthAPI"
jwt_audience: "AuthAPIUsers"
jwt_expiry_minutes: "60"